[package]
name = "ttf2image"
version = "0.1.0"
authors = ["g2_xpf <nameko.jack@gmail.com>"]
edition = "2018"

[dependencies]
rusttype = "0.7.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "*"
